version: "3"
services:
  mariadb:
    image: mariadb:10.3.16
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: todoapp
      TZ: EUROPE/BERLIN
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb-flush-method=fsync --innodb-use-native-aio=0

